name: QR_Test_Tubes
description: Information managment system in laboratory
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  auto_size_text: ^2.0.2+1
  path_provider: 1.2.0
  barcode_scan: ^1.0.0
  qr_flutter: ^2.1.0+55
  dynamic_theme: ^1.0.1
  http: 0.12.0+2
  json_annotation: ^2.4.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.2"
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon/icon.png"

flutter:

  uses-material-design: true
